<div class="IndexText">
	<h1>Registro de artistas - CastingZero </h1>
    <p>
    Somos una agencia de representación de artistas especializados en diversas disciplinas físicas. Contamos en nuestra base de datos con una amplia variedad de artistas circenses, bailarines, deportistas, actores y actrices de diversas edades (incluido niños).
    </p>
    <a href="ingreso" target="_self">
        <span>Registrarse</span>
    </a>
</div> 
<div class="clear"></div>
 