<div id="datos">
    DATOS EXTRAIDOS DE LA BASE DE DATOS:
    <br><br>
    <div class="conteAgencias">
    <?php
    $max = sizeof($this->dates_form);

    foreach ($this->dates_form as  $date_form) : 

              echo'<div class="persona">';
            if($this->escape($date_form->foto1)){
            echo '<img src="upload/'. $this->escape($date_form->foto1).'" width="200"/>';
            }
            if($this->escape($date_form->foto2)){
            echo '<img src="upload/'. $this->escape($date_form->foto2).'" width="200"/>';
            }
            if($this->escape($date_form->foto3)){
            echo '<img src="upload/'. $this->escape($date_form->foto3).'" width="200"/>';
            }
    ?>

            <br>
            <strong>Nombre: </strong><?php echo $this->escape($date_form->nombre); ?>
            <br>
            <strong>Apellido: </strong><?php echo $this->escape($date_form->apellido); ?>
            <br>
            <strong>telefono: </strong><?php echo $this->escape($date_form->telefono); ?>
            <br>
            <strong>cel: </strong><?php echo $this->escape($date_form->cel); ?>
            <br>
            <strong>Email: </strong><?php echo $this->escape($date_form->email); ?>
            <br>
            <strong> Atributos personales: </strong><br><?php echo $this->escape($date_form->Categorias); ?>
            <br>
            <strong>Acróbata/Gimnasta :</strong><br> <?php echo $this->escape($date_form->multiselect1); ?>
            <br>
            <strong>Artista circense:</strong> <br><?php echo $this->escape($date_form->multiselect2); ?>
            <br>
            <strong>Deportista:</strong><br> <?php echo $this->escape($date_form->multiselect3); ?>
            <br>
            <strong>Bailarín/a:<br> </strong><?php echo $this->escape($date_form->multiselect4); ?>
            <br>
            <strong>Músico:</strong> <br><?php echo $this->escape($date_form->multiselect5); ?>
            <br>
            <strong>Profesionales:</strong> <br><?php echo $this->escape($date_form->multiselect6); ?>
            <br>
            <strong>Sexo:</strong> <?php echo $this->escape($date_form->Sexo); ?>
           
            <br>
              <strong>id:</strong> <?php echo $this->escape($date_form->id); ?>
            <br>
             <?php echo'</div>';?>
    <?php 
        
    endforeach;
    ?>
    </div>
</div>