<div id="datos">
    DATOS EXTRAIDOS DE LA BASE DE DATOS:
    <br><br>
    <?php foreach ($this->dates_form as $date_form) : ?>
		    <?php if($this->escape($date_form->foto1)){
    		echo '<img src="upload/'. $this->escape($date_form->foto1).'" width="200"/>';
			}
			?>
		    <?php if($this->escape($date_form->foto2)){
    		echo '<img src="upload/'. $this->escape($date_form->foto2).'" width="200"/>';
			}
			?>
		    <?php if($this->escape($date_form->foto3)){
    		echo '<img src="upload/'. $this->escape($date_form->foto3).'" width="200"/>';
			}
			?>

            <br>
            telefono: <?php echo $this->escape($date_form->telefono); ?>
            <br>
            cel: <?php echo $this->escape($date_form->cel); ?>
            <br>
            Email: <?php echo $this->escape($date_form->email); ?>
            <br>
            Multiselect1: <?php echo $this->escape($date_form->multiselect1); ?>
            <br>
            Sexo: <?php echo $this->escape($date_form->Sexo); ?>
           
            <br>
              id: <?php echo $this->escape($date_form->id); ?>
            <br>
            
    <?php endforeach ?>
 
</div>