<?php //echo $this->layout()->content; ?>
<!doctype html><head>
<title>Casting Zero</title>
<link href="http://localhost/repo/CastingZero/public/stylesheets/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://localhost/repo/CastingZero/public/js/jquery-1.8.3.min.js"></script>
<?php echo $this->jQuery(); ?>
</head>
<body>
<div id="conte">
  <header style="margin-top:10px;">
  	<div class="logo"><img src="http://localhost/repo/CastingZero/public/images/logos-01.png"></div>
    <div class="log">
	<?php 
	echo Zend_Auth::getInstance()->getIdentity(); 
	$auth = Zend_Auth::getInstance();
		if ($auth->hasIdentity()) {
	?>
    |<a href="usuario/logout">logout</a>
	<?php } ?>
    </div>
  </header>
  <div class="clear"></div>
  <section>
    <div class="content" style="margin:10px"> <?php echo $this->layout()->content; ?></div>
  </section>
  <div class="clear"></div>
  <footer><p style="margin:10px">Footer<?php echo date('Y') ?></p></footer>
</div>
</body>
