<!doctype html><head>
<meta charset="UTF-8">
<title>Casting Zero</title>
<link href="http://www.castingzero.com/stylesheets/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://www.castingzero.com/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="http://www.castingzero.com/js/modernizr.js"></script>
<?php echo $this->jQuery(); ?>
</head>
<body>
<div id="conte">
  <header>
  	<div class="logo"><a href="http://www.castingzero.com/"><img src="http://www.castingzero.com/images/logo-01.png"></a></div>
    <div class="log">
	<?php 
	echo Zend_Auth::getInstance()->getIdentity(); 
	$auth = Zend_Auth::getInstance();
		if ($auth->hasIdentity()) {
	?>
    <a href="http://www.castingzero.com/usuario/logout">Logout</a>
	<?php }else{
		echo' <a href="http://www.castingzero.com/usuario/login">Login</a>';
	} ?>
    </div>
	<div class="clear"></div>
  </header>
  <section>
   <?php echo $this->layout()->content; ?>
  </section>
  <div class="clear"></div>
<script type="text/javascript" src="js/check.js"></script>
</div>
<div class="footer">
    <p>CastingZero -  Agencia de representación de artistas</p>
    <div class="visitSite" >
        <a href="http://www.castingzero.com.ar/" target="_blank">
            <span>Visitar CastingZero</span>
        </a>
    </div>
    <div class="clear"></div>
</div>
</body>
